# This is a basic workflow to help you get started with Actions

name: Manu Build OpenWRT in SSH

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
            inputs:
              OutPutFiles:
                description: 'Output File Name'     
                required: true
                default: 'OpenWrt'
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build-OpenWrt"
  Build-OpenWrt:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Installation depends
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq full-upgrade
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
          for i in $(ls /usr/bin/*-8); do sudo -E ln -sf $i ${i%%-8*}; done 
          sudo -E ln -sf /usr/include/asm-generic /usr/include/asm
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo -E swapoff -a
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile
          
# SSH Connect To Actions
#      - name: Setup Debug Session
#        uses: csexton/debugger-action@master
        
      - name: Clone Source
        run: |
          cd /home/runner
          bash ${GITHUB_WORKSPACE}/clone_source.sh
          sudo chown -R runner:runner lede
          
      - name: Before Build
        run: |
          /bin/bash ${GITHUB_WORKSPACE}/before_build.sh
          cp -fpR ${GITHUB_WORKSPACE}/. /home/runner/lede/

      - name: Upload firmware directory
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.OutPutFiles }}
          path: openwrt/bin/targets/*/*/*.*

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
